import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    title: 'Hoodie “Quiet Rhythm”',
    price: 5900,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop',
    description: 'Soft hoodie made of heavy cotton. Perfect for long walks with headphones.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '2',
    title: 'T-Shirt “Music Inside”',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop',
    description: 'Oversized t-shirt. A print you can hear.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '3',
    title: 'Longsleeve “Sound Wave”',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop',
    description: 'Longsleeve with a sound wave chart. For those on the same wavelength with music.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '5',
    title: 'Bomber “Vinyl Collector”',
    price: 8900,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=800&auto=format&fit=crop',
    description: 'Stylish bomber with pockets for 7-inch records (joke, but pockets are large).',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '6',
    title: 'Sweatshirt “Analog Warmth”',
    price: 4500,
    image: '/assets/products/analog-warmth.png',
    description: 'Sweatshirt in vintage amp color. Warm like tube sound.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '7',
    title: 'T-Shirt “Techno Bunker”',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop',
    description: 'Black t-shirt for dark rhythm lovers.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '11',
    title: 'Raincoat “Noise Cancelling”',
    price: 6500,
    image: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=800&auto=format&fit=crop',
    description: 'Heavy raincoat, blocking rain noise (a little).',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '10',
    title: 'Bucket Hat “Festival Season”',
    price: 2200,
    image: 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?q=80&w=800&auto=format&fit=crop',
    description: 'Protects from sun at summer festivals.',
    category: 'Clothing',
    sizes: ['S/M', 'L/XL'],
  },
  {
    id: '4',
    title: 'Cap “Studio Vibe”',
    price: 1900,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=800&auto=format&fit=crop',
    description: 'Minimalist cap for studio sessions and city days.',
    category: 'Accessories',
    sizes: ['One Size'],
  },
  {
    id: '8',
    title: 'Shopper “Crate Digger”',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    description: 'Durable shopper holding 20 records. Tested.',
    category: 'Accessories',
    sizes: ['One Size'],
  },
  {
    id: '9',
    title: 'Socks “L/R”',
    price: 900,
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?q=80&w=800&auto=format&fit=crop',
    description: 'Socks set with channel markings. So you don\'t mix up sides.',
    category: 'Accessories',
    sizes: ['36-39', '40-45'],
  },
  {
    id: '12',
    title: 'Backpack “Tour Life”',
    price: 7900,
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?q=80&w=800&auto=format&fit=crop',
    description: 'Spacious backpack for tours or trips with gear.',
    category: 'Accessories',
    sizes: ['One Size'],
  },
  {
    id: '13',
    title: 'Analog Polyphonic Synthesizer',
    price: 129000,
    image: 'https://images.unsplash.com/photo-1550291652-6ea9114a47b1?q=80&w=800&auto=format&fit=crop',
    description: 'Classic subtractive synthesis with modern reliability. 8-voice polyphony and rich modulation matrix.',
    category: 'Studio Gear',
  },
  {
    id: '14',
    title: 'Professional Studio Monitors',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=800&auto=format&fit=crop',
    description: 'Active bi-amplified speakers for critical listening. Transparent response and detailed imaging.',
    category: 'Studio Gear',
  },
  {
    id: '15',
    title: 'Reference Studio Headphones',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    description: 'Open-back design for natural soundstage and long mixing sessions without ear fatigue.',
    category: 'Studio Gear',
  },
  {
    id: '16',
    title: 'Portable FM Synthesizer & Sampler',
    price: 48000,
    image: 'https://images.unsplash.com/photo-1594122230689-45899d9e6f69?q=80&w=800&auto=format&fit=crop',
    description: 'Battery powered creative powerhouse. 4 tracks of sequencing, sampling, and sound design on the go.',
    category: 'Studio Gear',
  },
  {
    id: '17',
    title: 'Premium Audio Interface',
    price: 62000,
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=800&auto=format&fit=crop',
    description: 'Low-latency recording with industry-leading AD/DA converters and phantom-powered preamps.',
    category: 'Studio Gear',
  },
  {
    id: '18',
    title: 'Standalone Production Center',
    price: 115000,
    image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=800&auto=format&fit=crop',
    description: 'Everything you need for a beat. Pads, touchscreen, and built-in synthesizer engines.',
    category: 'Studio Gear',
  },
  {
    id: '19',
    title: 'Large Diaphragm Condenser Mic',
    price: 54000,
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop',
    description: 'The standard for professional vocals. Warm character with exceptional detail and clarity.',
    category: 'Studio Gear',
  },
  {
    id: '20',
    title: 'Flagship DJ Multi-Player',
    price: 245000,
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
    description: 'The industry standard for DJing. High-resolution touchscreen and rock-solid performance.',
    category: 'Studio Gear',
  },
  {
    id: '21',
    title: 'Tote Bag “Vinyl Life”',
    price: 1200,
    image: '/assets/products/vinyl-life.png',
    description: 'Canvas tote bag for your everyday carry. Light and durable.',
    category: 'Accessories',
    sizes: ['One Size'],
  },
  {
    id: '22',
    title: 'Beanie “Wavelog”',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=800&auto=format&fit=crop',
    description: 'Warm beanie for cold studio nights. Minimalist branding.',
    category: 'Clothing',
    sizes: ['One Size'],
  },
  {
    id: '23',
    title: 'Analog Drum Machine',
    price: 36000,
    image: '/assets/products/analog-drum-machine.png',
    description: 'Real analog punch. 6 distinct voices and a powerful sequencer.',
    category: 'Studio Gear',
  },
];
